services:
  webb:
    build:
      dockerfile: ./apps/webb/Dockerfile
    networks:
      - db
      - proxy
    depends_on:
      database:
        condition: service_healthy
    environment:
      - BETTER_AUTH_URL=https://localhost
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/listan?schema=public
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
  backend:
    build:
      dockerfile: ./apps/backend/Dockerfile
    networks:
      - db
      - proxy
    depends_on:
      database:
        condition: service_healthy
    environment:
      - BETTER_AUTH_URL=https://localhost
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/listan?schema=public
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
  database:
    container_name: postgres
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: listan
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d listan"]
      interval: 30s
      timeout: 10s
      retries: 5
  proxy:
    container_name: proxy
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
networks:
  proxy:
    driver: bridge
  db:
    driver: bridge
    internal: true
volumes:
  caddy_data:
  caddy_config:
  db:
