services:
  migrate:
    env_file:
      - .env
    container_name: migrate
    build:
      context: .
      dockerfile: ./packages/database/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/listan?schema=public
    networks:
      - db
  database:
    container_name: postgres
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: listan
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d listan"]
      interval: 10s
      timeout: 10s
      retries: 6
networks:
  db:
    driver: bridge
volumes:
  db:
